[package]
name = "hdr10plus_parser"
version = "0.2.4"
authors = ["quietvoid"]
edition = "2018"
license = "MIT"

[lib]
name = "tests"
path = "src/lib.rs"

[dependencies]
bitreader = "0.3.2"
serde = "1.0.101"
serde_json = "1.0.40"
indicatif = "0.12.0"
read-byte-slice = "0.1.2"
regex = "1.3.1"
clap = {version = "2.33.0", features = ["yaml"]}