[package]
name = "hdr10plus_parser"
version = "0.3.1"
authors = ["quietvoid"]
edition = "2018"
license = "MIT"

[dependencies]
structopt = "0.3.21"
serde = "1.0.118"
serde_json = "1.0.60"
indicatif = "0.15.0"
read-byte-slice = "0.1.2"
regex = "1.4.2"
ansi_term = "0.12.1"
deku = "0.9.2"
