[package]
name = "hdr10plus_tool"
version = "1.5.0"
authors = ["quietvoid"]
edition = "2021"
rust-version = "1.57.0"
license = "MIT"

[dependencies]
bitvec_helpers = "2.0.0"
hdr10plus = { path = "./hdr10plus", features = ["hevc", "json"] }
hevc_parser = { version = "0.5.2", features = ["hevc_io"] }

clap = { version = "4.0.23", features = ["derive", "wrap_help", "deprecated"] }
serde_json = { version = "1.0.87", features = ["preserve_order"] }
indicatif = "0.17.2"
anyhow = "1.0.66"
thiserror = "1.0.37"

[dev-dependencies]
assert_cmd = "2.0.6"
assert_fs = "1.0.9"
predicates = "2.1.2"

[[bin]]
name = "hdr10plus_tool"
path = "src/main.rs"

[workspace]
members = [
    "hdr10plus",
]
