[package]
name = "hdr10plus_tool"
version = "1.6.0"
authors = ["quietvoid"]
edition = "2021"
rust-version = "1.64.0"
license = "MIT"

[dependencies]
bitvec_helpers = { version = "3.1.2", default-features = false, features = ["bitstream-io"] }
hdr10plus = { path = "./hdr10plus", features = ["hevc", "json"] }
hevc_parser = { version = "0.6.1", features = ["hevc_io"] }

clap = { version = "4.3.19", features = ["derive", "wrap_help", "deprecated"] }
serde_json = { version = "1.0.103", features = ["preserve_order"] }
indicatif = "0.17.5"
anyhow = "1.0.72"
thiserror = "1.0.44"
plotters = { version = "0.3.5", default-features = false, features = ["bitmap_backend", "bitmap_encoder", "all_series"] }

[dev-dependencies]
assert_cmd = "2.0.10"
assert_fs = "1.0.12"
predicates = "3.0.3"

[[bin]]
name = "hdr10plus_tool"
path = "src/main.rs"

[workspace]
members = [
    "hdr10plus",
]

[features]
default = ["system-font"]
system-font = ["plotters/ttf"]
internal-font = ["plotters/ab_glyph"]
