[package]
name = "hdr10plus"
version = "1.1.0"
authors = ["quietvoid"]
edition = "2021"
rust-version = "1.56.0"
license = "MIT"
description = "HDR10+ metadata parsing and writing"
repository = "https://github.com/quietvoid/hdr10plus_tool/tree/master/hdr10plus"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec_helpers = "1.0.1"
anyhow = "1.0.52"
serde = { version = "1.0.133", features = ["derive"], optional = true }
serde_json = { version = "1.0.74", features = ["preserve_order"], optional = true }
hevc_parser = { version = "0.3.2", optional = true }

[features]
hevc = ["hevc_parser"]
json = ["serde", "serde_json"]

[package.metadata.docs.rs]
all-features = true
